### ISSUE TITLE
Can't install observing_squad

### ISSUE THREAD

**Issue by UranusLin** [multiversx/mx-chain-scripts#1]
I'm trying to set observing_squad on testnet via [mx-chain-scripts](https://github.com/multiversx/mx-chain-scripts), but it's have wrong, and can't start observing_squad.
```
./script.sh observing_squad
```
and will show
```
Cloning into the elrond-proxy-go and checking out tags/null...

Cloning into 'elrond-proxy-go'...
remote: Enumerating objects: 10849, done.
remote: Counting objects: 100% (321/321), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 10849 (delta 170), reused 311 (delta 170), pack-reused 10528
Receiving objects: 100% (10849/10849), 3.63 MiB | 477.00 KiB/s, done.
Resolving deltas: 100% (7279/7279), done.
error: pathspec 'tags/null' did not match any file(s) known to git
```
then end script, but script create folder `elrond-nodes` and `elrond-utils` are all empty, it's anything problem here?

**Comment by valentin-lup** [comment]
Hey ! Nice to see people are proactive ! Scripts will be updated today to work with the all new rebranded node and proxy repo.
Will let you know when ready ! Thanks !

**Comment by iulianpascalau** [comment]
should work now
